importing libraries

In [40]:
import os
import ast
import pandas as pd
import numpy as np

In [41]:
os.chdir("C:\\Users\\virat\\Desktop\\model")

In [42]:

movies=pd.read_csv('tmdb_movies_data.csv')
movies = movies.fillna("")

In [43]:
movies

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,0.080598,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,,Bruce Brown,,...,"The Endless Summer, by Bruce Brown, is one of ...",95,Documentary,Bruce Brown Films,6/15/1966,11,7.4,1966,0.000000e+00,0.000000e+00
10862,20379,tt0060472,0.065543,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,,John Frankenheimer,Cinerama sweeps YOU into a drama of speed and ...,...,Grand Prix driver Pete Aron is fired by his te...,176,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,12/21/1966,20,5.7,1966,0.000000e+00,0.000000e+00
10863,39768,tt0060161,0.065141,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,,Eldar Ryazanov,,...,An insurance agent who moonlights as a carthie...,94,Mystery|Comedy,Mosfilm,1/1/1966,11,6.5,1966,0.000000e+00,0.000000e+00
10864,21449,tt0061177,0.064317,0,0,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,,Woody Allen,WOODY ALLEN STRIKES BACK!,...,"In comic Woody Allen's film debut, he took the...",80,Action|Comedy,Benedict Pictures Corp.,11/2/1966,22,5.4,1966,0.000000e+00,0.000000e+00
10865,22293,tt0060666,0.035919,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,,Harold P. Warren,It's Shocking! It's Beyond Your Imagination!,...,A family gets lost on the road and stumbles up...,74,Horror,Norm-Iris,11/15/1966,15,1.5,1966,1.276423e+05,0.000000e+00

In [44]:
movies=movies[['id','imdb_id','original_title', 'genres', 'overview', 'cast', 'director', 'keywords']]

In [45]:
#movies

In [46]:
movies["cast"] = movies["cast"].str.split("|")

movies["genres"] = movies["genres"].str.split("|")
movies["keywords"] = movies["keywords"].str.split("|")
movies["director"] = movies["director"].apply(lambda x: [x])

C:\Users\virat\AppData\Local\Temp\ipykernel_11512\2377992258.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["cast"] = movies["cast"].str.split("|")
C:\Users\virat\AppData\Local\Temp\ipykernel_11512\2377992258.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["genres"] = movies["genres"].str.split("|")
C:\Users\virat\AppData\Local\Temp\ipykernel_11512\2377992258.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["keywords"] = movies["keywords"].str.split("|")
C:\Users\virat\AppData\Local\Temp\ipykernel_11512\2377992258.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["director"] = movies["director"].apply(lambda x: [x])

In [47]:
#movies

In [48]:
movies["overview"] = movies["overview"].fillna("").astype(str)
movies["overview"] = movies["overview"].apply(lambda x: x.split())

C:\Users\virat\AppData\Local\Temp\ipykernel_11512\113335971.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["overview"] = movies["overview"].fillna("").astype(str)
C:\Users\virat\AppData\Local\Temp\ipykernel_11512\113335971.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["overview"] = movies["overview"].apply(lambda x: x.split())

In [49]:
#movies

In [50]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['director']=movies['director'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])


movies["cast"] = movies["cast"].apply(lambda x: x[:3] if isinstance(x, list) else x)

C:\Users\virat\AppData\Local\Temp\ipykernel_11512\3234186474.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\virat\AppData\Local\Temp\ipykernel_11512\3234186474.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\virat\AppData\Local\Temp\ipykernel_11512\3234186474.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['director']=movies['director'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\virat\AppData\Local\Temp\ipykernel_11512\3234186474.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\virat\AppData\Local\Temp\ipykernel_11512\3234186474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["cast"] = movies["cast"].apply(lambda x: x[:3] if isinstance(x, list) else x)

In [51]:
#movies

creating the tags column

In [52]:
movies['tags']= movies['overview'] +movies['genres'] +movies['cast']+movies['director']+movies['keywords']

C:\Users\virat\AppData\Local\Temp\ipykernel_11512\2613618176.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']= movies['overview'] +movies['genres'] +movies['cast']+movies['director']+movies['keywords']

In [53]:
movies

,id,imdb_id,original_title,genres,overview,cast,director,keywords,tags
0,135397,tt0369610,Jurassic World,"[Action, Adventure, ScienceFiction, Thriller]","[Twenty-two, years, after, the, events, of, Ju...","[ChrisPratt, BryceDallasHoward, IrrfanKhan]",[ColinTrevorrow],"[monster, dna, tyrannosaurusrex, velociraptor,...","[Twenty-two, years, after, the, events, of, Ju..."
1,76341,tt1392190,Mad Max: Fury Road,"[Action, Adventure, ScienceFiction, Thriller]","[An, apocalyptic, story, set, in, the, furthes...","[TomHardy, CharlizeTheron, HughKeays-Byrne]",[GeorgeMiller],"[future, chase, post-apocalyptic, dystopia, au...","[An, apocalyptic, story, set, in, the, furthes..."
2,262500,tt2908446,Insurgent,"[Adventure, ScienceFiction, Thriller]","[Beatrice, Prior, must, confront, her, inner, ...","[ShaileneWoodley, TheoJames, KateWinslet]",[RobertSchwentke],"[basedonnovel, revolution, dystopia, sequel, d...","[Beatrice, Prior, must, confront, her, inner, ..."
3,140607,tt2488496,Star Wars: The Force Awakens,"[Action, Adventure, ScienceFiction, Fantasy]","[Thirty, years, after, defeating, the, Galacti...","[HarrisonFord, MarkHamill, CarrieFisher]",[J.J.Abrams],"[android, spaceship, jedi, spaceopera, 3d]","[Thirty, years, after, defeating, the, Galacti..."
4,168259,tt2820852,Furious 7,"[Action, Crime, Thriller]","[Deckard, Shaw, seeks, revenge, against, Domin...","[VinDiesel, PaulWalker, JasonStatham]",[JamesWan],"[carrace, speed, revenge, suspense, car]","[Deckard, Shaw, seeks, revenge, against, Domin..."
...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,The Endless Summer,[Documentary],"[The, Endless, Summer,, by, Bruce, Brown,, is,...","[MichaelHynson, RobertAugust, Lord'TallyHo'Ble...",[BruceBrown],"[surfer, surfboard, surfing]","[The, Endless, Summer,, by, Bruce, Brown,, is,..."
10862,20379,tt0060472,Grand Prix,"[Action, Adventure, Drama]","[Grand, Prix, driver, Pete, Aron, is, fired, b...","[JamesGarner, EvaMarieSaint, YvesMontand]",[JohnFrankenheimer],"[carrace, racing, formula1]","[Grand, Prix, driver, Pete, Aron, is, fired, b..."
10863,39768,tt0060161,Beregis Avtomobilya,"[Mystery, Comedy]","[An, insurance, agent, who, moonlights, as, a,...","[InnokentiySmoktunovskiy, OlegEfremov, GeorgiZ...",[EldarRyazanov],"[car, trolley, stealingcar]","[An, insurance, agent, who, moonlights, as, a,..."
10864,21449,tt0061177,"What's Up, Tiger Lily?","[Action, Comedy]","[In, comic, Woody, Allen's, film, debut,, he, ...","[TatsuyaMihashi, AkikoWakabayashi, MieHama]",[WoodyAllen],[spoof],"[In, comic, Woody, Allen's, film, debut,, he, ..."
10865,22293,tt0060666,Manos: The Hands of Fate,[Horror],"[A, family, gets, lost, on, the, road, and, st...","[HaroldP.Warren, TomNeyman, JohnReynolds]",[HaroldP.Warren],"[fire, gun, drive, sacrifice, flashlight]","[A, family, gets, lost, on, the, road, and, st..."

creating new dataframe for "title","movie_id"and"Tags" column

In [54]:
df = movies[['id','imdb_id', 'original_title','tags']]

In [55]:
df

,id,imdb_id,original_title,tags
0,135397,tt0369610,Jurassic World,"[Twenty-two, years, after, the, events, of, Ju..."
1,76341,tt1392190,Mad Max: Fury Road,"[An, apocalyptic, story, set, in, the, furthes..."
2,262500,tt2908446,Insurgent,"[Beatrice, Prior, must, confront, her, inner, ..."
3,140607,tt2488496,Star Wars: The Force Awakens,"[Thirty, years, after, defeating, the, Galacti..."
4,168259,tt2820852,Furious 7,"[Deckard, Shaw, seeks, revenge, against, Domin..."
...,...,...,...,...
10861,21,tt0060371,The Endless Summer,"[The, Endless, Summer,, by, Bruce, Brown,, is,..."
10862,20379,tt0060472,Grand Prix,"[Grand, Prix, driver, Pete, Aron, is, fired, b..."
10863,39768,tt0060161,Beregis Avtomobilya,"[An, insurance, agent, who, moonlights, as, a,..."
10864,21449,tt0061177,"What's Up, Tiger Lily?","[In, comic, Woody, Allen's, film, debut,, he, ..."
10865,22293,tt0060666,Manos: The Hands of Fate,"[A, family, gets, lost, on, the, road, and, st..."

convertung the list data of column into a string

In [56]:
df['tags']=df['tags'].apply(lambda x:" ".join(x))

C:\Users\virat\AppData\Local\Temp\ipykernel_11512\2493417758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x:" ".join(x))

In [57]:
df

,id,imdb_id,original_title,tags
0,135397,tt0369610,Jurassic World,Twenty-two years after the events of Jurassic ...
1,76341,tt1392190,Mad Max: Fury Road,An apocalyptic story set in the furthest reach...
2,262500,tt2908446,Insurgent,Beatrice Prior must confront her inner demons ...
3,140607,tt2488496,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...
4,168259,tt2820852,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...
...,...,...,...,...
10861,21,tt0060371,The Endless Summer,"The Endless Summer, by Bruce Brown, is one of ..."
10862,20379,tt0060472,Grand Prix,Grand Prix driver Pete Aron is fired by his te...
10863,39768,tt0060161,Beregis Avtomobilya,An insurance agent who moonlights as a carthie...
10864,21449,tt0061177,"What's Up, Tiger Lily?","In comic Woody Allen's film debut, he took the..."
10865,22293,tt0060666,Manos: The Hands of Fate,A family gets lost on the road and stumbles up...

In [58]:
df['tags']=df['tags'].apply(lambda x:x.lower())

C:\Users\virat\AppData\Local\Temp\ipykernel_11512\3373437752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x:x.lower())

In [59]:
df

,id,imdb_id,original_title,tags
0,135397,tt0369610,Jurassic World,twenty-two years after the events of jurassic ...
1,76341,tt1392190,Mad Max: Fury Road,an apocalyptic story set in the furthest reach...
2,262500,tt2908446,Insurgent,beatrice prior must confront her inner demons ...
3,140607,tt2488496,Star Wars: The Force Awakens,thirty years after defeating the galactic empi...
4,168259,tt2820852,Furious 7,deckard shaw seeks revenge against dominic tor...
...,...,...,...,...
10861,21,tt0060371,The Endless Summer,"the endless summer, by bruce brown, is one of ..."
10862,20379,tt0060472,Grand Prix,grand prix driver pete aron is fired by his te...
10863,39768,tt0060161,Beregis Avtomobilya,an insurance agent who moonlights as a carthie...
10864,21449,tt0061177,"What's Up, Tiger Lily?","in comic woody allen's film debut, he took the..."
10865,22293,tt0060666,Manos: The Hands of Fate,a family gets lost on the road and stumbles up...

finally steming the repeated words

In [60]:
import nltk 
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)
df['tags']=df['tags'].apply(stem)

C:\Users\virat\AppData\Local\Temp\ipykernel_11512\2202691384.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(stem)

In [61]:
# df.info()

here all the data is in its final state

NOW TO START THE VECTORIZATION

In [62]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(df['tags']).toarray()

In [63]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10866, 5000))

In [64]:
# cv.get_feature_names_out()

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
similarity=cosine_similarity(vectors)

In [67]:
similarity[0]

array([1.        , 0.18195634, 0.15      , ..., 0.        , 0.08304548,
       0.        ], shape=(10866,))

In [68]:
def recommend(movie):
    movie_index=df[df['original_title']==movie].index[0]
    proper_index=movie_index.item()

    distance= similarity[proper_index]

    movies_list=sorted(list(enumerate(distance)),reverse=True,  key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(df.iloc[i[0]].original_title)

In [69]:
recommend("Pirates of the Caribbean: At World's End")

Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: The Curse of the Black Pearl
The Last Airbender
Pirates of the Caribbean: On Stranger Tides
The Snowman

In [70]:
import pickle

In [71]:

pickle.dump(df.to_dict(),open('movies_dict_final.pkl','wb'))

In [72]:
pickle.dump(similarity,open('similarity_final.pkl','wb'))

In [73]:
df

,id,imdb_id,original_title,tags
0,135397,tt0369610,Jurassic World,twenty-two year after the event of jurass park...
1,76341,tt1392190,Mad Max: Fury Road,an apocalypt stori set in the furthest reach o...
2,262500,tt2908446,Insurgent,beatric prior must confront her inner demon an...
3,140607,tt2488496,Star Wars: The Force Awakens,"thirti year after defeat the galact empire, ha..."
4,168259,tt2820852,Furious 7,deckard shaw seek reveng against domin toretto...
...,...,...,...,...
10861,21,tt0060371,The Endless Summer,"the endless summer, by bruce brown, is one of ..."
10862,20379,tt0060472,Grand Prix,grand prix driver pete aron is fire by hi team...
10863,39768,tt0060161,Beregis Avtomobilya,an insur agent who moonlight as a carthief ste...
10864,21449,tt0061177,"What's Up, Tiger Lily?","in comic woodi allen' film debut, he took the ..."
10865,22293,tt0060666,Manos: The Hands of Fate,a famili get lost on the road and stumbl upon ...

In [76]:
imdb_code = "tt3896198"   # example: The Matrix
row = movies[movies["imdb_id"] == imdb_code]
print(row)

Empty DataFrame
Columns: [id, imdb_id, original_title, genres, overview, cast, director, keywords, tags]
Index: []